version: '2'
services:
        oscobol:
                image: norisaka/opensource_cobol
                tty: true
                environment:
                        COBCPY: /oscobol/cpy
                volumes:
                        - ./src:/oscobol/src
                        - ./cpy:/oscobol/cpy

        db:
                image: postgres:9.6

networks:
        default:
                

